default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  url: "postgresql://postgres:postgres@localhost:3000/test_phase-3-sinatra-react-project"

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>