default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  url: "postgresql://postgres:postgres@localhost:3000/test_phase-3-sinatra-react-project"

production:
  adapter: postgresql
  encoding: unicode
  database: production
  host: <%= ENV[‘DATABASE_HOST’] %>
  pool: 5
  production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>